### PR TITLE
Fixed license definition

### PR DESCRIPTION
**Pull request by sergeyklay**
Hello,

I fixed BSD 3-Clause License definition.

### CODE REVIEW

**Comment by hartwork** [comment]
I get the idea of the first half but what's the idea with the second half?
Since this is legal text, to be honest I'm not sure yet I want to touch it all.

**Comment by sergeyklay** [comment]
@hartwork In fact there is a canonical form of the BSD 3-Clause license :)

- https://spdx.org/licenses/BSD-3-Clause.html
- https://opensource.org/licenses/BSD-3-Clause
- https://choosealicense.com/licenses/bsd-3-clause

**Comment by hartwork** [comment]
Hello again,

sorry it took me so long to act on this. I still wonder when that change from owner to holder in the text happened and how the mix in here came to be, precisely. Anyway, I have mass-applied a version of this change with [justified test](http://www.nicemice.net/par/) in #86 now. What do you think?

Best, Sebastian

**Comment by sergeyklay** [comment]
Looks good to me

**Comment by hartwork** [comment]
Thanks for the review and for bringing this up!

**Pull request closed without merging**
