### PR TITLE
Support making UriUri* instance independent (for #77)

### PR DESCRIPTION
**Pull request by hartwork**
For #77

@veselov this is a first rough version. API docs are yet to come, formatting might change, function names might change. Would be great to have your review on this. Thanks!

### CODE REVIEW

**Comment by veselov** [comment]
I think this looks perfect :)

**Comment by hartwork** [comment]
> I think this looks perfect :)

Thanks!

@veselov I have done some polishing and added API documentation now. I would merge status quo into `master` unless you see any new or outstanding issues in here. Ready to merge?

**Comment by veselov** [comment]
I've tried using the merge request commit, and calling new function from my code, it works just as expected, thank you!

**Comment by hartwork** [comment]
Merged now, thanks for review and testing!

**Pull request merged**
